[Log]
Level = "debug"

[WebServer]
AllowOrigins = "*"
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[Database]
MaxIdleConns = 10
MaxOpenConns = 20

[Feature]
LogPoller = true

[[EVM]]
ChainID = "31337"
Enabled = true

[[EVM.Nodes]]
Name = "anvil"
HTTPURL = "http://anvil:8545"
WSURL = "ws://anvil:8545"
