#!/usr/bin/env bash
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd -- "$here/.." && pwd)"

# Defaults: validate all random models generated by emf-random for b2c.ecore.
xmi_dir="${1:-$here/emf-random/b2c}"
ecore="${2:-$here/b2c.ecore}"
ocl="${3:-$here/check.ocl}"
report_dir="${4:-$here/ocl-report}"

resolve_existing() {
  local p="$1"
  if [[ "$p" = /* ]]; then
    echo "$p"
    return
  fi
  if [[ -e "$root/$p" || -d "$root/$p" ]]; then
    realpath "$root/$p"
    return
  fi
  if [[ -e "$here/$p" || -d "$here/$p" ]]; then
    realpath "$here/$p"
    return
  fi
  echo "$root/$p"
}

resolve_output_dir() {
  local p="$1"
  if [[ "$p" = /* ]]; then
    realpath -m "$p"
    return
  fi
  if [[ -d "$root" ]]; then
    realpath -m "$root/$p"
    return
  fi
  realpath -m "$p"
}

xmi_dir="$(resolve_existing "$xmi_dir")"
ecore="$(resolve_existing "$ecore")"
ocl="$(resolve_existing "$ocl")"
report_dir="$(resolve_output_dir "$report_dir")"

echo "[1/1] Batch validate XMI models with Eclipse OCL (Complete OCL)"
echo "  XMI dir:    $xmi_dir"
echo "  Ecore:      $ecore"
echo "  OCL:        $ocl"
echo "  Report dir: $report_dir"

mkdir -p "$report_dir"

cd "$root"

mvn -q -f "$here/ocl-runner-tycho/pom.xml" \
  -Dtycho.disableP2Mirrors=true \
  -Decore="$ecore" -Docl="$ocl" \
  -DxmiDir="$xmi_dir" -DxmiGlob=".xmi" \
  -DreportDir="$report_dir" \
  -DwritePerModelJson=true \
  -DfailOnViolation=false \
  integration-test

echo "Done. See: $report_dir/report.json"
