# Generated by Django 3.2.25 on 2026-01-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-e4af5b741ef349ec9eec08f19d3441f4', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-0213ec57dd7e4bfba8f4f95aa492f302', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
