# Generated by Django 3.2.25 on 2026-01-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260120_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-af337184966e4bd9968e843ea0a77171', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-6bd8f01a801b4997bca32beff8989d52', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
