# Generated by Django 3.2.25 on 2026-01-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20260121_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-6d14fdafe50041c5b76940e9b1c29eee', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-e418e8a0383f48b4ba9b0068e5a2500a', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
