# Generated by Django 3.2.25 on 2026-01-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260121_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-3d5455de1b6e4bdea5ee9c594143b714', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-1f42a8d3a99140368fe35d6229419dce', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
