# Generated by Django 3.2.25 on 2026-01-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20260121_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-7c31671479704686ae74dab1e87770bd', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-92f850d8e2ef47bf90cdfa98bcfa6d62', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
