# Generated by Django 3.2.25 on 2026-01-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20260121_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-258d1bd3323e4c4382322ef2738b1c28', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-2867fedfa4ae456a88a4a2037e96f70a', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
