# Generated by Django 3.2.25 on 2026-01-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20260121_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-d1050e3671564fa6ad97a1ce4aeabf53', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-0e51c6916302457d87cf633df1497222', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
