# Generated by Django 3.2.25 on 2026-01-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20260121_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-7edc92d7871c4813a51c81fb4f8f648c', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-e5b8794a91414e2e8e23e7f35b71a10d', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
