# Generated by Django 3.2.25 on 2026-01-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20260121_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-d7d6113b86f44d3da0e9941a97f48411', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-b553b37da56d4b48a5faf6e6537a55a5', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
