# Generated by Django 3.2.25 on 2026-01-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20260121_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-c392a7121011412891d3c57eb9c112db', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-bd6b2074128144a782df7e890c56c534', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
