# Generated by Django 3.2.25 on 2026-01-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20260121_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-7a7627b2f7764f559df61b8afe8145a0', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-b36a11a999344329a1cd75e11121f7e5', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
