server.port=8080
server.servlet.context-path=/

# Spring Banner
spring.banner.charset=UTF-8
spring.banner.location=classpath:banner.txt

# Logging configuration
logging.level.com.chaincollab.dmn.server=INFO
logging.level.org.camunda=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Maximum file size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
