#!/usr/bin/env bash
# Lightweight helper that mirrors the legacy startrc aliases/functions.

_devtools_is_sourced=0
if [ -n "${ZSH_VERSION:-}" ]; then
  case $ZSH_EVAL_CONTEXT in
    *:file) _devtools_is_sourced=1 ;;
  esac
elif [ -n "${BASH_VERSION:-}" ]; then
  if [ "${BASH_SOURCE[0]}" != "$0" ]; then
    _devtools_is_sourced=1
  fi
fi

if [ "$_devtools_is_sourced" -eq 0 ]; then
  set -euo pipefail
fi

if [ -n "${ZSH_VERSION:-}" ]; then
  SCRIPT_SOURCE="${(%):-%N}"
else
  SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
fi

REPO_ROOT="$(cd "$(dirname "$SCRIPT_SOURCE")/.." && pwd)"
# Project paths
BACKEND_DIR="$REPO_ROOT/src/backend"
DASHBOARD_DIR="$REPO_ROOT/src/dashboard"
AGENT_DIR="$REPO_ROOT/src/agent/docker-rest-agent"
FRONT_DIR="$REPO_ROOT/src/front"

run_clean() {
  if [ -n "${ZSH_VERSION:-}" ]; then
    setopt local_options null_glob
  fi
  echo "[dev] Remove agent storage"
  sudo rm -rf "$REPO_ROOT/src/agent/docker-rest-agent/storage/"*
  sudo rm -rf "$REPO_ROOT/src/agent/docker-rest-agent/CA_related/storage/fabric-ca-servers/"*

  echo "[dev] Remove backend opt/cello"
  sudo rm -rf "$BACKEND_DIR/opt/cello/"*

  echo "[dev] Remove backend pgdata"
  sudo chmod -R 777 "$BACKEND_DIR/pgdata" 2>/dev/null || true
  sudo rm -rf "$BACKEND_DIR/pgdata/"*

  echo "[dev] Remove autogenerated migrations"
  find "$BACKEND_DIR/api/migrations" -type f -name '*_auto_*.py' -exec sudo rm -f {} \;

  echo "[dev] Remove docker containers matching *.com/org"
  while read -r name; do
    [ -n "$name" ] || continue
    docker stop "$name" >/dev/null 2>&1 || true
    docker rm "$name" >/dev/null 2>&1 || true
  done < <(docker ps -a --format "{{.Names}}" | grep -E 'com$|edu.cn$|tech.cn$|org.com$' || true)

  echo "[dev] Remove cello-postgres container"
  docker stop cello-postgres >/dev/null 2>&1 || true
  docker rm cello-postgres >/dev/null 2>&1 || true

  docker container prune -f
  docker volume prune -f

  echo "[dev] Remove FireFly stacks"
  if command -v ff >/dev/null 2>&1; then
    ff list | grep 'cello_' | xargs -r -I{} sh -c "echo 'y' | ff remove {}" || true
  fi
  rm -rf "$HOME/.firefly/stacks"/cello_* 2>/dev/null || true
}

start_dashboard() {
  (cd "$DASHBOARD_DIR" && npm run start)
}

start_front() {
  (cd "$FRONT_DIR" && npm run dev -- --host)
}

start_agent() {
  local venv_path="$AGENT_DIR/venv"
  local alt_venv="$AGENT_DIR/.venv"
  if [ ! -d "$venv_path" ] && [ -d "$alt_venv" ]; then
    venv_path="$alt_venv"
  fi
  if [ ! -d "$venv_path" ]; then
    echo "[dev] Creating agent virtualenv..."
    (cd "$AGENT_DIR" && python3 -m venv "$venv_path")
    echo "[dev] Installing agent requirements..."
    (cd "$AGENT_DIR" && source "$venv_path/bin/activate" && pip install -r requirements.txt)
  fi
  (cd "$AGENT_DIR" && source "$venv_path/bin/activate" && exec gunicorn server:app -c ./gunicorn.conf.py)
}

start_database() {
  (cd "$BACKEND_DIR" && docker-compose up -d)
}

prepare_api() {
  (cd "$BACKEND_DIR" && source venv/bin/activate && python3 manage.py makemigrations && python3 manage.py migrate)
}

start_api() {
  (cd "$BACKEND_DIR" && source venv/bin/activate && python manage.py runserver)
}

export_er() {
  (cd "$BACKEND_DIR" && source venv/bin/activate && python manage.py graph_models -a -g -o er.png)
}

export_er_dot() {
  (cd "$BACKEND_DIR" && source venv/bin/activate && python manage.py graph_models -a -o er.dot)
}

start_translator() {
  (cd "$HOME/translator-springboot" && mvn spring-boot:run)
}

new_start_translator() {
  local translator_root="$REPO_ROOT/src/newTranslator"
  local venv_path="$translator_root/.venv"
  local uvicorn_bin="uvicorn"
  if [ -x "$venv_path/bin/uvicorn" ]; then
    uvicorn_bin="$venv_path/bin/uvicorn"
  elif [ -f "$venv_path/bin/activate" ]; then
    # Fall back to activating venv if uvicorn script is missing.
    source "$venv_path/bin/activate"
  fi
  if ! command -v "$uvicorn_bin" >/dev/null 2>&1; then
    echo "[dev] uvicorn not found. Please install dependencies in $venv_path (e.g. source $venv_path/bin/activate && pip install -r requirements.txt)."
    return 1
  fi
  (cd "$translator_root" && export PYTHONPATH="$translator_root/.." && exec "$uvicorn_bin" newTranslator.service.api:app --reload --host 0.0.0.0 --port 9999)
}

start_chor_app() {
  (cd "$HOME/chor_js_modify" && npm run dev)
}

start_backend() {
  start_database
  sleep 1
  prepare_api
  start_api
}

add_host_mapping() {
  if [ $# -eq 0 ]; then
    echo "Usage: $0 host <hostname> [hostname...]"
    return 1
  fi
  for host in "$@"; do
    echo "127.0.0.1 $host" | sudo tee -a /etc/hosts >/dev/null
    echo "＋ Added $host to /etc/hosts"
  done
}

_dev_usage() {
  cat <<'EOF'
Usage: devtools.sh <command> [args]
Commands:
  clean             - run clean.sh from repo root (sudo)
  dashboard         - npm start for src/dashboard
  front             - npm run dev for src/front (with --host)
  agent             - start docker-rest-agent (gunicorn)
  db                - docker-compose up backend
  prepare-api       - makemigrations + migrate
  api               - run Django dev server
  backend           - start_database + prepare_api + start_api
  export-er         - generate er.png
  export-er-dot     - generate er.dot
  translator        - mvn spring-boot:run (~/translator-springboot)
  new-translator    - uvicorn newTranslator.service.api:app --reload (src/newTranslator)
  chor              - npm run dev (~/chor_js_modify)
  host <names...>   - append hostnames to /etc/hosts pointing to 127.0.0.1
EOF
}

_dev_dispatch() {
  local cmd="${1:-}"
  if [ $# -gt 0 ]; then
    shift
  fi

  case "$cmd" in
    clean) run_clean ;;
    dashboard) start_dashboard ;;
    front) start_front ;;
    agent) start_agent ;;
    db) start_database ;;
    prepare-api) prepare_api ;;
    api) start_api ;;
    backend) start_backend ;;
    export-er) export_er ;;
    export-er-dot) export_er_dot ;;
    translator) start_translator ;;
    new-translator) new_start_translator ;;
    chor) start_chor_app ;;
    host) add_host_mapping "$@" ;;
    ""|help|-h|--help) _dev_usage ;;
    *) echo "Unknown command: $cmd"; _dev_usage; return 1 ;;
  esac
}

dev() {
  _dev_dispatch "$@"
}

if [ "$_devtools_is_sourced" -eq 0 ]; then
  dev "$@"
else
  alias clean="dev clean"
fi
