version: "3.8"

services:
  cdmn-node1:
    build:
      context: ./cdmn-python-server
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${CDMN_BASE_IMAGE:-python:3.9-slim}
    image: chaincollab-cdmn-server:latest
    container_name: cdmn-node1
    restart: unless-stopped
    environment:
      - FLASK_RUN_PORT=5000
      - OCR_LISTENER_ENABLED=true
      - OCR_RPC_URL=http://mybootnode:8545
      - OCR_AGGREGATOR_ADDRESS=${OCR_AGGREGATOR_ADDRESS}
    ports:
      - "8081:5000"
    networks:
      - existing_network

  cdmn-node2:
    build:
      context: ./cdmn-python-server
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${CDMN_BASE_IMAGE:-python:3.9-slim}
    image: chaincollab-cdmn-server:latest
    container_name: cdmn-node2
    restart: unless-stopped
    environment:
      - FLASK_RUN_PORT=5000
      - OCR_LISTENER_ENABLED=true
      - OCR_RPC_URL=http://mybootnode:8545
      - OCR_AGGREGATOR_ADDRESS=${OCR_AGGREGATOR_ADDRESS}
    ports:
      - "8082:5000"
    networks:
      - existing_network

  cdmn-node3:
    build:
      context: ./cdmn-python-server
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${CDMN_BASE_IMAGE:-python:3.9-slim}
    image: chaincollab-cdmn-server:latest
    container_name: cdmn-node3
    restart: unless-stopped
    environment:
      - FLASK_RUN_PORT=5000
      - OCR_LISTENER_ENABLED=true
      - OCR_RPC_URL=http://mybootnode:8545
      - OCR_AGGREGATOR_ADDRESS=${OCR_AGGREGATOR_ADDRESS}
    ports:
      - "8083:5000"
    networks:
      - existing_network

  cdmn-node4:
    build:
      context: ./cdmn-python-server
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${CDMN_BASE_IMAGE:-python:3.9-slim}
    image: chaincollab-cdmn-server:latest
    container_name: cdmn-node4
    restart: unless-stopped
    environment:
      - FLASK_RUN_PORT=5000
      - OCR_LISTENER_ENABLED=true
      - OCR_RPC_URL=http://mybootnode:8545
      - OCR_AGGREGATOR_ADDRESS=${OCR_AGGREGATOR_ADDRESS}
    ports:
      - "8084:5000"
    networks:
      - existing_network

networks:
  existing_network:
    external: true
    name: cello-net
